export const chart = [
    "Sabrina Carpenter",
    "Billie Eilish",
    "Taylor Swift",
    "LINKIN PARK",
    "Lady Gaga",
    "Bruno Mars",
    "KAROL G",
    "Feid",
    "The Weeknd",
    "Chappell Roan",
    "Adele",
    "Teddy Swims",
    "Bad Bunny",
    "Jimin",
    "Travis Scott",
    "Charli XCX",
    "Coldplay",
    "FloyyMenor",
    "Benson Boone",
    "Post Malone",
    "Eminem",
    "Cris Mj",
    "Peso Pluma",
    "Ed Sheeran",
    "Ariana Grande",
    "Kendrick Lamar",
    "Hozier",
    "Shaboozey",
    "Drake",
    "Myke Towers",
    "Kapo",
    "Zach Bryan",
    "Tate McRae",
    "SZA",
    "Olivia Rodrigo",
    "Morgan Wallen",
    "Rauw Alejandro",
    "GIMS",
    "Kanye West",
    "Lana Del Rey",
    "Playboi Carti",
    "Tito Double P",
    "Gracie Abrams",
    "Dua Lipa",
    "David Guetta",
    "Imagine Dragons",
    "Ninho",
    "Asake",
    "Sevdaliza",
    "*NSYNC",
    "Chris Brown",
    "Mrs. GREEN APPLE",
    "Katy Perry",
    "Metro Boomin",
    "Fuerza Regida",
    "Hanumankind",
    "Shiva",
    "Frank Ocean",
    "Matuê",
    "Future",
    "JHAYCO",
    "Adam Port",
    "Burna Boy",
    "Luke Combs",
    "Disturbed",
    "Semicenk",
    "Rihanna",
    "Rema",
    "The Kid LAROI",
    "Jung Kook",
    "Oasis",
    "V",
    "Myles Smith",
    "Artemas",
    "Pritam",
    "Fred again..",
    "周杰伦",
    "Arctic Monkeys",
    "Bernadya",
    "Beyoncé",
    "Megan Thee Stallion",
    "MACAN",
    "Blessd",
    "NewJeans",
    "Dasha",
    "AYLIVA",
    "Arijit Singh",
    "Ayra Starr",
    "One Direction",
    "CYRIL",
    "Junior H",
    "Calvin Harris",
    "LE SSERAFIM",
    "aespa",
    "The Neighbourhood",
    "Noah Kahan",
    "ANNA",
    "Sachin-Jigar",
    "A-Reece",
    "Natanael Cano",
    "Grupo Frontera",
    "Keinemusik",
    "Stryv",
    "Malachiii",
    "Orso",
    "Geolier",
    "Pabllo Vittar",
    "Luck Ra",
    "OneRepublic",
    "Maluma",
    "Kalmi",
    "Yseult",
    "Amitabh Bhattacharya",
    "Karan Aujla",
    "Tiakola",
    "J Balvin",
    "Tiago PZK",
    "Emilia",
    "Julión Álvarez y su Norteño Banda",
    "Anuel AA",
    "Romeo Santos",
    "Manuel Turizo",
    "Trueno",
    "J Abdiel",
    "Don Toliver",
    "HUGEL",
    "Fleetwood Mac",
    "Mark Ambor",
    "SDM",
    "Cigarettes After Sex",
    "Tommy Richman",
    "Tom Odell",
    "Lost Frequencies",
    "Mora",
    "Gunna",
    "Elyanna",
    "Maisak",
    "Jala Brat",
    "Davido",
    "Daft Punk",
    "Pitbull",
    "back number",
    "Kabza De Small",
    "Rvssian",
    "Mas Musiq",
    "Carin Leon",
    "TINI",
    "Jul",
    "iZaak",
    "Valentino Merlo",
    "Gigi Perez",
    "Yorssy",
    "BTS",
    "Werenoi",
    "Dadju",
    "Anirudh Ravichander",
    "keshi",
    "Sia",
    "P!nk",
    "London Grammar",
    "David Gilmour",
    "Leto",
    "Marshmello",
    "Central Cee",
    "YOASOBI",
    "Milo j",
    "Kman 6ixx",
    "Meghan Trainor",
    "DJ Maphorisa",
    "Fireboy DML",
    "Lvbel C5",
    "Charlie Puth",
    "Yandel",
    "Mahalini",
    "Luis R Conriquez",
    "Plan B",
    "Jere Klein",
    "Alphaville",
    "Aarne",
    "Justin Bieber",
    "Big One",
    "BLOK3",
    "Diljit Dosanjh",
    "Snow Patrol",
    "MC 張天賦",
    "Juicy Luicy",
    "Big Baby Tape",
    "Maes",
    "Aventura",
    "A.R. Rahman",
    "Rod Wave",
    "Lord Huron",
    "周杰倫",
    "Ty Dolla $ign",
    "Boza",
    "Topic",
    "Shawn Mendes",
    "PARTYNEXTDOOR",
    "Dei V",
    "BOYNEXTDOOR",
    "AP Dhillon",
    "Lil Baby",
    "Baby Lullaby Academy",
    "Fally Ipupa",
    "Tayna",
    "Kenshi Yonezu",
    "Lewis Capaldi",
    "Shakira",
    "Jelly Roll",
    "DAY6",
    "Arash",
    "Yo Yo Honey Singh",
    "Pharrell",
    "Jordan Adetunji",
    "Lazza",
    "SQUASH",
    "Masicka",
    "LISA",
    "DESH",
    "Miyagi",
    "¥$",
    "Tems",
    "Maria Becerra",
    "Kelvin Momo",
    "Omah Lay",
    "Ozuna",
    "Lomiiel",
    "9mice",
    "NEWS",
    "Grelo",
    "Luis Miguel",
    "Camila Cabello",
    "Jakone",
    "Madhubanti Bagchi",
    "LACAZETTE",
    "Lacrim",
    "AC/DC",
    "Neton Vega",
    "Little Simz",
    "Miley Cyrus",
    "ONE OK ROCK",
    "Jay Wheeler",
    "Los Ángeles Azules",
    "Tainy",
    "VAUNDY",
    "ANH TRAI \"SAY HI\"",
    "Nirvana",
    "The Goo Goo Dolls",
    "MoBlack",
    "Vishal Mishra",
    "bambi",
    "Bouss",
    "Ski Aggu",
    "Buba Corelli",
    "Usimamane",
    "Vybz Kartel",
    "Kai Angel",
    "Don Omar",
    "Gazo",
    "Michael Jackson",
    "21 Savage",
    "Sam Smith",
    "Henrique & Juliano",
    "Stray Kids",
    "BINI",
    "ATL Jacob",
    "Daddy Yankee",
    "Journey",
    "Tony Effe",
    "Ado",
    "UZI",
    "TUL8TE",
    "Nanpa Básico",
    "Latto",
    "Niska",
    "Young Miko",
    "Jaxomy",
    "Kraff Gad",
    "Arcángel",
    "Byron Messia",
    "Damso",
    "AL SHAMI",
    "Wiz Khalifa",
    "Maroon 5",
    "RajahWild",
    "Doja Cat",
    "Beéle",
    "Tyla",
    "The Chainsmokers",
    "Harry Styles",
    "Anuv Jain",
    "wave to earth",
    "Tayc",
    "Pink Floyd",
    "Gusttavo Lima",
    "Era7capone",
    "Ovy On The Drums",
    "WizKid",
    "Daecolm",
    "Chronic Law",
    "Navai",
    "Senidah",
    "Gabito Ballesteros",
    "Lin-Manuel Miranda",
    "Roxy Dekker",
    "Sfera Ebbasta",
    "Guy2Bezbar",
    "Chencho Corleone",
    "Ke Personajes",
    "sanah",
    "Prince Swanny",
    "Amy Winehouse",
    "Quevedo",
    "Shilpa Rao",
    "JENNIE",
    "Apache 207",
    "Óscar Maydon",
    "Jessica Shy",
    "NICKI NICOLE",
    "MHD",
    "Djo",
    "Scotts Maphuma",
    "Booba",
    "The Script",
    "Shubh",
    "Luis Alfonso",
    "Azahriah",
    "Salif Keïta",
    "twenty one pilots",
    "RM",
    "RIIZE",
    "Leemckrazy",
    "Anitta",
    "Shirin David",
    "Babasha",
    "Benj Pasek",
    "VEN1",
    "Nik Tendo",
    "SAIKO",
    "MEOVV",
    "Chris Stapleton",
    "Tyler ICU",
    "Clean Bandit",
    "DYSTINCT",
    "Ирина Кайратовна",
    "The La Planta",
    "Omar Montes",
    "Daniel Caesar",
    "Beny Jr",
    "Ayed",
    "Camilo",
    "Justin Paul",
    "Эндшпиль",
    "Lucky Brown",
    "Flo Rida",
    "Q' Lokura",
    "J. Cole",
    "XXXTENTACION",
    "Young Leosia",
    "Himra",
    "Basta",
    "Grupo Firme",
    "Hugh Jackman",
    "Yan Block",
    "Zé Neto",
    "Cristiano",
    "Seyi Vibez",
    "KATSEYE",
    "데이식스",
    "Jorge & Mateus",
    "Ruger",
    "Tananai",
    "Ultimo",
    "Hov1",
    "Entremares",
    "(G)I-DLE",
    "Yorushika",
    "La Oreja de Van Gogh",
    "Morat",
    "Aimyon",
    "Radiohead",
    "James Arthur",
    "Tiësto",
    "Mabel Matiz",
    "Emre Fel",
    "LL COOL J",
    "Nicky Jam",
    "PLK",
    "Hande Yener",
    "Andrea Bocelli",
    "ANNA ASTI",
    "BL3SS",
    "De La Rose",
    "Ofenbach",
    "Shenseea",
    "ROSALÍA",
    "Fontaines D.C.",
    "The Cranberries",
    "BoyPee",
    "Murilo Huff",
    "Separ",
    "Charly García",
    "Maoli",
    "Yuvan Shankar Raja",
    "Eladio Carrión",
    "Kidd Voodoo",
    "Rels B",
    "Bnxn",
    "Jeff Satur",
    "Troye Sivan",
    "Bolaget",
    "El Alfa",
    "Atif Aslam",
    "Odeya",
    "SEVENTEEN",
    "6ix9ine",
    "Macklemore",
    "Hugo",
    "Tedua",
    "Hindia",
    "AKDO",
    "Simge",
    "Nick Cave & The Bad Seeds",
    "Franglish",
    "Jay Chou",
    "Ryan Lewis",
    "Valiant",
    "The Killers",
    "Viktor Sheen",
    "HammAli",
    "Gülşen",
    "Keblack",
    "RAYE",
    "Key-Key",
    "BLACKPINK",
    "Frenna",
    "Melendi",
    "BAEKHYUN",
    "Hamza",
    "Fujii Kaze",
    "Popcaan",
    "Niki",
    "Odetari",
    "Laufey",
    "Nile Rodgers",
    "Kiliana",
    "Mthunzi",
    "Mitski",
    "Omer Adam",
    "Chimbala",
    "Annalisa",
    "Oskoow",
    "Ryflo",
    "Пошлая Молли",
    "Becky G",
    "Malaysia Vasudevan",
    "Jason Mraz",
    "Guilherme",
    "TJ Monterde",
    "Voyage",
    "Dionela",
    "Tulus",
    "Kid Yugi",
    "Capo Plaza",
    "Sal Priadi",
    "JC Reyes",
    "Beyond",
    "Mc IG",
    "Christian Nodal",
    "Darkoo",
    "Poshlaya Molly",
    "Divya Kumar",
    "Skolim",
    "Simone Mendes",
    "Fiji",
    "ILLIT",
    "Mark Ronson",
    "Tyler, The Creator",
    "Keung To 姜濤",
    "Grše",
    "Alkaline",
    "Chino Pacas",
    "Kevin AMF",
    "BABYMONSTER",
    "Tony Boy",
    "Fridayy",
    "Clairo",
    "Rammstein",
    "Hev Abi",
    "Natasha Bedingfield",
    "Bryson Tiller",
    "Indochine",
    "uniqe",
    "Michael Marcagi",
    "Elton John",
    "Kizo",
    "Gibbs",
    "TitoM",
    "Ndotz"
]